// Catalan translations for Valoració d'Ofertes
// Extracted from ca.json

export const STRINGS = {
	header: {
		title: "Evaluador d'ofertes de Licitacions",
		subtitle: "Sistema potenciat amb IA per a l'Avaluació de Licitacions",
		newTender: "Nova licitació",
		admin: "Admin",
		resetConfirm: "Estàs segur que vols resetar tota la informació? Aquesta acció no es pot desfer.",
		resetTitle: "Reseteja la pàgina per començar una nova avaluació",
	},
	settings: {
		language: "Idioma",
	},
	documents: {
		sectionTitle: "Documents de la Licitació",
		specificationsTitle: "Plecs de Condicions *",
		specificationsTooltip: "Aquí s'han d'afegir els Plecs Tècnics, els Plecs Administratius o un sol document que els agrupi els dos.",
	},
	fileUpload: {
		dragOrClick: "Arrossega arxius aquí o fes clic per seleccionar",
		processingFiles: "Processant arxius...",
		filesProcessed: "Arxius Processats ({count})",
		totalCharacters: "Total: {count} caràcters",
		minimumContent: "Contingut mínim extret",
		processedCorrectly: "Processat correctament",
		corrected: "✓ Corregit",
		removeFile: "Eliminar arxiu",
		characters: "{count} caràcters",
		viewPreview: "👁️ Veure previsualització del contingut extret",
		errorProcessing: "Error processant arxius",
		closeMessage: "Tancar missatge",
	},
	proposals: {
		sectionTitle: "Proposta a Avaluar *",
		selectLot: "Selecciona el lot:",
		lot: "Lot",
		fileTypes: "PDF, DOC, DOCX - Màxim 10MB",
		proposalsPerLot: "Propostes per Lot",
		noProposalSubmitted: "No s'ha presentat proposta per aquest lot",
	},
	lots: {
		individualEvaluation: "Avaluació Individual per Lots",
		evaluated: "Avaluat",
		evaluating: "Avaluant...",
		evaluateLot: "Avaluar Lot",
		processingWithAI: "Processant amb IA...",
		availableLots: "Lots Disponibles:",
		lotsIdentified: "{count, plural, one {# lot identificat} other {# lots identificats}}",
		singleLot: "Lot Únic",
		noProposals: "Sense propostes",
		proposals: "{count} {count, plural, one {proposta} other {propostes}}",
		extractingInfo: "Extraient informació dels lots del plec de condicions...",
		thisMayTakeSeconds: "Això pot trigar uns segons...",
		addSpecifications: "Afegeix el Plec de Condicions per continuar",
		onceProcessed: "Un cop processat, podràs afegir les propostes per cada lot identificat.",
		fileTypes: "PDF, DOC, DOCX - Màxim 10MB",
	},
	evaluation: {
		evaluateAllLots: "Avaluar Tots els Lots",
		evaluatingAllLots: "Avaluant tots els lots...",
		evaluatingLot: "Avaluant lot...",
		processingFiles: "Processant arxius...",
		noProposals: "No hi ha propostes per avaluar",
		lotsWithProposals: (lotCount: number, proposalCount: number) => `${lotCount} ${lotCount === 1 ? "lot" : "lots"} amb ${proposalCount} ${proposalCount === 1 ? "proposta" : "propostes"}`,
		lotsWithoutProposals: (count: number) => `${count} ${count === 1 ? "lot" : "lots"} sense propostes`,
		omittingLots: (count: number) => `ometent ${count} ${count === 1 ? "lot" : "lots"} sense propostes`,
		totalLotsIdentified: (count: number) => `Total: ${count} ${count === 1 ? "lot identificat" : "lots identificats"}`,
		evaluationError: "Error d'avaluació",
		intelligentEvaluation: "Avaluació Intel·ligent",
		intelligentEvaluationDesc: "L'avaluació completa processarà automàticament només els lots amb propostes presentades. També pots avaluar lots individuals utilitzant els botons específics a continuació",
	},
	loader: {
		progressive: {
			title: "Avaluant Licitació",
			lotProgress: "Lot {current} de {total}",
			starting: "Iniciant avaluació...",
			processing: "Processant amb intel·ligència artificial",
		},
		single: {
			title: "Avaluant Lot {lot}",
			analyzing: "Analitzant propostes amb IA",
		},
		comparison: {
			title: "Comparant Propostes",
			subtitle: "Lot {lot}: {count} propostes",
			generating: "Generant anàlisi comparatiu",
		},
	},
	results: {
		title: "Resultats de l'Avaluació",
		summary: "Resum",
		downloadPDF: "Descarregar Informe PDF",
		downloadAll: "Descarregar Tot",
		totalLots: "Total de Lots",
		proposalsEvaluated: "Propostes Avaluades",
		recommendations: "Recomanacions",
		noResults: "No hi ha resultats disponibles",
		viewDetails: "Veure Detalls",
		evaluationTitle: "Resultat de l'Avaluació",
		evaluationSubtitle: "Avaluació completada amb èxit | Anàlisi detallada disponible",
		lotsEvaluated: "Lots Avaluats",
		companiesIdentified: "Empreses Identificades",
		generalAnalysis: "Anàlisi General",
		evaluationCompleted: "Avaluació Completada amb Èxit",
		allReportsAvailable: "Tots els informes es poden descarregar des de la secció de cada lot. Cada lot inclou els informes individuals de les seves propostes i, si és possible, l'informe comparatiu entre empreses.",
		individualReportsInLots: "Informes individuals dins de cada lot",
		comparisonForMultipleProposals: "Comparació disponible per lots amb múltiples propostes",
		individual: {
			title: "Resultats d'Avaluació Individual",
			subtitle: (count: number) => `${count} ${count === 1 ? "lot avaluat" : "lots avaluats"} individualment | Anàlisi detallada disponible`,
			lotsEvaluated: "Lots Avaluats",
			proposalsEvaluated: "Propostes Avaluades",
			companiesIdentified: "Empreses Identificades",
			percentIdentified: (percent: number) => `${percent}% identificades`,
			noProposals: "Sense propostes",
		},
	},
	comparison: {
		title: "Comparació de Propostes",
		compare: "Comparar",
		comparing: "Comparant...",
		analysis: "Anàlisi Comparatiu",
	},
	common: {
		loading: "Carregant...",
		error: "Error",
		success: "Èxit",
		cancel: "Cancel·lar",
		confirm: "Confirmar",
		close: "Tancar",
		save: "Desar",
		delete: "Eliminar",
		edit: "Editar",
		back: "Enrere",
		next: "Següent",
		finish: "Finalitzar",
	},
	errors: {
		generic: "S'ha produït un error. Si us plau, torna-ho a intentar.",
		fileUpload: "Error pujant l'arxiu",
		fileProcess: "Error processant documents",
		evaluation: "Error durant l'avaluació",
		noProposals: "No hi ha propostes per avaluar",
		completeRequired: "Si us plau, completa tots els camps obligatoris",
		noProposalsInLot: "No hi ha propostes per al lot {lotNumber}",
		errorEvaluatingLot: "Error avaluant lot {lotNumber}",
		unknownError: "Error desconegut",
		noProposalsInAnyLot: "No hi ha propostes per evaluar en cap lot",
		errorDuringEvaluation: "Error durant l'avaluació",
	},
	summary: {
		proposalsEvaluated: (totalProposals: number, evaluatedLots: number) => `S'han avaluat ${totalProposals} propostes distribuïdes en ${evaluatedLots} ${evaluatedLots === 1 ? "lot" : "lots"}.`,
		companiesIdentified: (companiesIdentified: number, totalProposals: number) => `S'han identificat automàticament ${companiesIdentified} empreses de ${totalProposals} propostes presentades.`,
		lotsWithoutProposals: (count: number) => `${count} ${count === 1 ? "lot no ha rebut propostes" : "lots no han rebut propostes"}.`,
		evaluationCompleted: "L'avaluació ha estat completada amb èxit utilitzant criteris específics per cada lot.",
		reviewRecommendation: (multipleLots: boolean) => `Es recomana revisar ${multipleLots ? "individualment cada lot i les seves respectives avaluacions" : "detingudament l'avaluació realitzada"}.`,
		considerRetender: (count: number) => `Cal considerar si relicitar ${count === 1 ? "el lot que no ha rebut propostes" : "els lots que no han rebut propostes"} o revisar els requisits per facilitar la participació.`,
		detailedAnalysis: "Cada lot avaluat ha utilitzat criteris específics i requereix una anàlisi detallada per prendre decisions informades sobre l'adjudicació.",
	},
	proposalEvaluation: {
		criteriaEvaluation: "Avaluació per Criteris",
		proposalAnalysis: "Anàlisi de la Proposta",
		strengths: "Punts Forts",
		improvements: "Àrees de Millora",
		references: "Referències",
		scores: {
			compleix_exitosament: "Compleix exitosament",
			regular: "Regular",
			insuficient: "Insuficient",
		},
	},
	lotEvaluation: {
		lot: "Lot",
		notSubmitted: "No presentat",
		noProposalSubmitted: "No s'ha presentat proposta per aquest lot",
		cannotEvaluateWithoutDocs: "No es pot realitzar l'avaluació sense documentació",
		companyNotIdentified: "empresa no identificada",
		proposals: "propostes",
		proposal: "proposta",
		identified: "identificades",
		criteriaEvaluated: "criteris avaluats",
		comparisonBetweenCompanies: "Comparació entre Empreses",
		detailedComparativeAnalysis: "Anàlisi comparatiu detallat entre {count} propostes",
		compare: "Comparar",
		downloadReports: "Descarregar Informes del Lot {lotNumber}",
		individualReportsPerProposal: "Informes Individuals per Proposta:",
	},
	pdf: {
		titles: {
			evaluationReport: "INFORME D'AVALUACIÓ",
			comparisonReport: "INFORME COMPARATIU",
			detailedEvaluation: "AVALUACIÓ DETALLADA",
			generalInfo: "INFORMACIÓ GENERAL",
			evaluatedCriteria: "CRITERIS AVALUATS",
			globalRanking: "RÀNKING GLOBAL D'EMPRESES",
			comparisonTable: "TAULA COMPARATIVA PER CRITERIS",
			detailedCriteriaAnalysis: "ANÀLISI DETALLADA PER CRITERIS",
			detailedCriteriaEvaluation: "AVALUACIÓ DETALLADA PER CRITERIS",
			defaultTitle: "INFORME D'AVALUACIÓ",
			defaultSubtitle: "DE PROPOSTA DE LICITACIÓ",
			comparisonSubtitle: "DE PROPOSTES DE LICITACIÓ",
			executiveSummary: "RESUM EXECUTIU DE LA COMPARACIÓ",
			generalSummary: "RESUM GENERAL",
			generalAnalysis: "ANÀLISI GENERAL",
		},
		labels: {
			title: "Títol:",
			expedient: "Expedient:",
			contractingEntity: "Entitat Contractant:",
			evaluationDate: "Data d'avaluació:",
			evaluatedCompany: "Empresa avaluada:",
			evaluatedDocument: "Document avaluat:",
			lot: "Lot:",
			evaluatedCriteria: "Criteris avaluats:",
			companyIdentification: "Identificació empresa:",
			comparedProposals: "Propostes comparades:",
			identifiedCompanies: "Empreses identificades:",
			comparedLot: "Lot comparat:",
			additionalContext: "Context Addicional:",
			proposalSummary: "Resum de la Proposta:",
			proposalAnalysis: "Anàlisi de la Proposta:",
			globalScore: "Puntuació Global:",
			strengths: "Punts Forts:",
			weaknesses: "Punts Febles:",
			recommendations: "Recomanacions:",
			criterion: "Criteri:",
			evaluatedLots: "Lots avaluats:",
			totalEvaluatedProposals: "Total propostes avaluades:",
			totalEvaluatedCriteria: "Total criteris avaluats:",
			evaluation: "Avaluació",
			analysis: "Anàlisi",
			references: "Referències:",
		},
		status: {
			noProposalSubmitted: "No s'ha presentat proposta per aquest lot",
			notSpecified: "No especificat",
			notIdentifiedAutomatically: "No identificada automàticament",
			companyNotIdentified: "Nota: Empresa no identificada automàticament",
			company: "[EMPRESA]",
			document: "[DOCUMENT]",
			enterprise: "[E]",
			documentShort: "[D]",
		},
		positions: {
			first: "1r",
			second: "2n",
			third: "3r",
			nth: "{position}è",
		},
		filenames: {
			evaluation: "avaluacio",
			comparison: "comparacio_lot",
			proposal: "proposta",
		},
		scores: {
			compleix_exitosament: "Compleix exitosament",
			regular: "Regular",
			insuficient: "Insuficient",
		},
		footer: {
			aiDeclaration:
				"Declaració sobre l'ús d'intel·ligència artificial: Aquest informe ha estat generat parcialment mitjançant l'ús d'un sistema d'intel·ligència artificial, en compliment del Reglament (UE) 2024/1083 del Parlament Europeu i del Consell. El sistema utilitzat no actua de manera autònoma ni substitueix la responsabilitat humana. El contingut ha de ser revisat abans de prendre decisions vinculants, i no pot ser emprat com a documentació definitiva sense aquesta revisió.",
			legendEnterprise: "[E] = Empresa identificada",
			legendDocument: "[D] = Document sense empresa",
		},
	},
}

// Helper function to replace placeholders in strings
export function replaceVars(str: string, vars: Record<string, string>): string {
	if (!str || typeof str !== "string") return str
	let result = str
	Object.keys(vars).forEach((key) => {
		result = result.replace(new RegExp(`\\{${key}\\}`, "g"), vars[key])
	})
	return result
}
